'use client';

import React, { useEffect, useState } from 'react';
import { VaultPerformanceSheet } from './VaultPerformanceSheet';

interface VaultDepositSheetProps {
  isOpen: boolean;
  onClose: () => void;
  vaultName: string;
  vaultIcon: string;
  isSignedIn?: boolean;
  onSignIn?: () => void;
}

export function VaultDepositSheet({ isOpen, onClose, vaultName, vaultIcon, isSignedIn = false, onSignIn }: VaultDepositSheetProps) {
  const [isAnimating, setIsAnimating] = useState(false);
  const [activeTab, setActiveTab] = useState<'deposit' | 'withdraw'>('deposit');
  const [showPerformance, setShowPerformance] = useState(false);

  useEffect(() => {
    if (isOpen) {
      setIsAnimating(true);
    }
  }, [isOpen]);

  if (!isOpen && !isAnimating) return null;

  return (
    <>
      <div className="fixed inset-0 z-50">
        {/* Backdrop */}
        <div 
          className={`fixed inset-0 bg-black/50 transition-opacity duration-300 ${
            isOpen ? 'opacity-100' : 'opacity-0'
          }`}
          onClick={onClose}
        />

        {/* Bottom Sheet */}
        <div 
          className={`fixed inset-x-0 bottom-0 transform transition-transform duration-300 ease-out ${
            isOpen ? 'translate-y-0' : 'translate-y-full'
          }`}
          onTransitionEnd={() => {
            if (!isOpen) setIsAnimating(false);
          }}
        >
          <div className="bg-[#1B2022] rounded-t-[32px] max-h-[90vh] overflow-y-auto">
            <div className="px-6 pt-8 pb-10">
              {/* Header */}
              <div className="flex justify-between items-center mb-6">
                <div className="flex items-center space-x-3">
                  <img
                    src={vaultIcon}
                    alt={vaultName}
                    width={32}
                    height={32}
                    className="w-8 h-8 rounded-full"
                  />
                  <h2 className="text-2xl font-semibold text-white">{vaultName}</h2>
                </div>
                <button 
                  onClick={onClose}
                  className="p-1 text-[#A4A6A7] hover:text-white"
                >
                  <svg className="w-6 h-6" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>

              {/* Divider */}
              <div className="h-px bg-[#494D4E]/20 -mx-6 mb-6" />

              {/* Tabs */}
              <div className="flex rounded-xl bg-[#2A2D2E] p-1 mb-6">
                <button
                  onClick={() => setActiveTab('deposit')}
                  className={`flex-1 py-3 rounded-lg text-base transition-colors ${
                    activeTab === 'deposit'
                      ? 'bg-white text-black font-bold'
                      : 'text-[#A4A6A7] hover:text-white font-normal'
                  }`}
                >
                  Deposit
                </button>
                <button
                  onClick={() => setActiveTab('withdraw')}
                  className={`flex-1 py-3 rounded-lg text-base transition-colors ${
                    activeTab === 'withdraw'
                      ? 'bg-white text-black font-bold'
                      : 'text-[#A4A6A7] hover:text-white font-normal'
                  }`}
                >
                  Withdraw
                </button>
              </div>

              {/* Description */}
              <div className="text-[#A4A6A7] text-base mb-8">
                Deposit USDC to receive the yield-bearing nAsset, nUSDC.
                Yield accrues from the interest generated by depositing
                USDC from this vault to the nUSDC vault.{' '}
                <button 
                  onClick={() => setShowPerformance(true)}
                  className="text-[#31C1BF] hover:text-[#31C1BF]/80 underline"
                >
                  Learn More
                </button>
              </div>

              {/* Balance Info */}
              <div className="flex justify-between items-center mb-4">
                <span className="text-[#A4A6A7]">You Give</span>
                <div className="flex items-center gap-2">
                  <div className="flex items-center gap-2 text-[#A4A6A7]">
                    <img
                      src="/wallet.png"
                      alt="Wallet"
                      width={20}
                      height={20}
                      className="w-5 h-5"
                    />
                    <span>10,000 ($3,000)</span>
                  </div>
                  <button className="px-3 py-1 rounded-full border border-[#31C1BF] text-[#31C1BF] text-sm hover:bg-[#31C1BF]/10 transition-colors">
                    Max
                  </button>
                </div>
              </div>

              {/* Input Amount */}
              <div className="bg-[#2A2D2E] rounded-xl p-4 mb-6">
                <div className="flex items-center justify-between">
                  <input
                    type="text"
                    placeholder="0.00"
                    className="bg-transparent text-2xl text-white w-full outline-none"
                  />
                  <div className="flex items-center space-x-2 bg-[#343739] rounded-lg px-3 py-2">
                    <div className="w-6 h-6 bg-[#31C1BF]/20 rounded-full flex items-center justify-center">
                      <img
                        src={activeTab === 'deposit' ? vaultIcon : "/USDC.png"}
                        alt={activeTab === 'deposit' ? vaultName : "nUSDC"}
                        width={20}
                        height={20}
                        className="w-5 h-5 rounded-full"
                      />
                    </div>
                    <span className="text-white font-medium">
                      {activeTab === 'deposit' ? vaultName : "nUSDC"}
                    </span>
                  </div>
                </div>
              </div>

              {/* You Get */}
              <div className="mb-6">
                <div className="text-[#A4A6A7] mb-4">You Get</div>
                <div className="bg-[#2A2D2E] rounded-xl p-4">
                  <div className="flex items-center justify-between">
                    <div className="text-2xl text-white opacity-50">0.00</div>
                    <div className="flex items-center space-x-2 bg-[#343739] rounded-lg px-3 py-2">
                      <div className="w-6 h-6 bg-[#31C1BF]/20 rounded-full flex items-center justify-center">
                        <img
                          src={activeTab === 'deposit' ? "/USDC.png" : vaultIcon}
                          alt={activeTab === 'deposit' ? "nUSDC" : vaultName}
                          width={20}
                          height={20}
                          className="w-5 h-5 rounded-full"
                        />
                      </div>
                      <span className="text-white font-medium">
                        {activeTab === 'deposit' ? "nUSDC" : vaultName}
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Action Button */}
              <button 
                onClick={isSignedIn ? undefined : onSignIn}
                className="w-full py-4 bg-[#31C1BF] hover:bg-[#31C1BF]/90 rounded-full text-white text-lg font-medium transition-colors"
              >
                {isSignedIn 
                  ? (activeTab === 'deposit' ? 'Deposit Token' : 'Withdraw Token')
                  : 'Sign In'
                }
              </button>
            </div>
          </div>
        </div>
      </div>

      <VaultPerformanceSheet
        isOpen={showPerformance}
        onClose={() => setShowPerformance(false)}
        vaultName={vaultName}
        vaultIcon={vaultIcon}
      />
    </>
  );
} 